### ISSUE TITLE
Switch stationery icon to osm-carto icon

### ISSUE THREAD

**Issue by math1985** [gmgeo/osmic#49]
Would it be an idea to switch the stationery icon to the icon from osm-carto ([link](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/stationery-14.svg))?

I think it would be good to synchronise both projects as much as possible, for example to avoid confusion for users who use the osmic icons in JOSM.

Both the icon here and on osm-carto are clear icons, and nothing is really wrong with either of them, but if I had to choose one, I'd prefer the one currently in osm-carto as it is slightly more intuitive to me what types of products this type of shop sells.

Just a suggestion, if you prefer the osmic icon, feel free to close this issue!

**Comment by nebulon42** [comment]
I agree that it is beneficial to have as much similar icons as possible. I also like the paperclip idea, but to me this icon is a bit too lightweight compared to the other icons. That is why I have created a different version with the pen. Out of this reason I'm rather reluctant to change it.

**Comment by math1985** [comment]
I see what you mean. For me [in context](http://www.openstreetmap.org/#map=19/51.51686/-0.08655) it works fine, so I also don't see a reason to change it in osm-carto.
