### ISSUE TITLE
Icon produces error message, when trying to import into Adobe Illustrator

### ISSUE THREAD

**Issue by StefanBrand** [gmgeo/osmic#53]
Hi, when I drag and drop the `airport-14.svg` into Adobe Illustrator CC 2015, I get the following error message:

>This SVG is invalid. Validate it before opening.

#### Steps to reproduce
1. Sign in to Github.
1. Download `airport-14.svg` by "Save target as" in Firefox.
2. Drag&Drop it into a document in Adobe Illustrator
3. Error message pops up.

#### My system
Windows 10 64bit
Adobe Illustrator CC 2015 (19.0.0 64bit)

#### Other
Inspecting the file in a text editor, I found that the svg had a lot of metadata in it (including my Github name, for example).
Trying to load the svg into jakearchibald/svgomg (https://jakearchibald.github.io/svgomg/) gave me `Load failed: Unexpected close tag`.

**Comment by nebulon42** [comment]
I think you inadvertently downloaded the web page that Github outputs when you click on airport-14.svg. 

Try this:
1. Click on airport-14.svg
2. Above the preview select "Raw"
3. Download the output that you get by saving the document

Alternatively you can also click on "Clone or download" at the main page of the repository and select "Download ZIP". You should get a ZIP archive containing all icons.

This validator shows that the SVG in question seems to be valid: https://validator.nu/?doc=https%3A%2F%2Fraw.githubusercontent.com%2Fgmgeo%2Fosmic%2Fmaster%2Ftransport%2Fairport-14.svg&laxtype=yes

**Comment by StefanBrand** [comment]
That must be it! Thank you!
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 14. Dezember 2016 22:17:20 MEZ schrieb Michael Glanznig <notifications@github.com>:
>I think you inadvertently downloaded the web page that Github outputs
>when you click on airport-14.svg. 
>
>Try this:
>1. Click on airport-14.svg
>2. Above the preview select "Raw"
>3. Download the output that you get by saving the document
>
>Alternatively you can also click on "Clone or download" at the main
>page of the repository and select "Download ZIP". You should get a ZIP
>archive containing all icons.
>
>This validator shows that the SVG in question seems to be valid:
>https://validator.nu/?doc=https%3A%2F%2Fraw.githubusercontent.com%2Fgmgeo%2Fosmic%2Fmaster%2Ftransport%2Fairport-14.svg&laxtype=yes
